#jumtlxekbbaxhdqr

server:
  port: 7075

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: overdose
    password: 123
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  mail:
    username: ${socialmediamailusername}
    password: ${socialmediapasword}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

rabbitmq:
  registerMailQueue: mail-queue