server:
  port: 7073

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      username: java6user
      password: root
      database: postdb
jwt:
  secretkey: ${my-secret-key}
  audience: ${audience}
  issuer: ${ULAS2_ISSUER}
